version: 0.0
os: linux
files:
 - source: /
   destination: /home/guidetoadulting/public_html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/invoke_node.sh
      timeout: 10000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 500
      runas: root
