module.exports = {

  OPEN_MENU: 'OPEN_MENU',
  CLOSE_MENU: 'CLOSE_MENU',
  TOGGLE_MENU: 'TOGGLE_MENU',

  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_PAGES: 'RECEIVE_PAGES',
  RECEIVE_SETTINGS: 'RECEIVE_SETTINGS'
};
